Repository hitsz-ids/duetector, pull requests merged in 2023-10, with the labels that each got.

#82 Feature: Support OTel Collector
  README.md
  README_zh.md
  dev-tools/start-docs-host.sh
  docs/source/collectors/index.rst
  docs/source/collectors/otel.rst
  duetector/collectors/models.py
  duetector/collectors/otel.py
  duetector/collectors/register.py
  duetector/static/config.toml
  duetector/utils.py
  pyproject.toml
  tests/config.toml
  tests/test_db_collector.py
  tests/test_otel_collector.py
Labels: enhancement

#84 Draft: Case of MNIST
  docs/draft/case-mnist/README.md
  docs/draft/case-mnist/imgs/Analysis.png
  docs/draft/case-mnist/imgs/DataStream.png
  docs/draft/case-mnist/imgs/ProcessionandHooks.png
  docs/draft/case-mnist/imgs/command0.png
  docs/draft/case-mnist/imgs/command1.png
  docs/draft/case-mnist/imgs/command2.png
  docs/draft/case-mnist/report.md
  docs/draft/case-mnist/src/mnist.py
  docs/draft/case-mnist/src/result.md
Labels: documentation

#90 Add docs for oTel(jager backend)
  README.md
  README_zh.md
  docs/how-to/images/jaeger.png
  docs/how-to/intergration-with-otel.md
  duetector/collectors/models.py
  duetector/collectors/otel.py
  duetector/tracers/base.py
Labels: documentation, enhancement
